#ENC[AES256_GCM,data:I5TrVpSh6CJ9hEDBZbiOr+uu9ONwPb54RZbVQG3/cBBi8nUm+vTv5LttNgc/hcLbRGplnVAeXA==,iv:Rk1/RGzSuS/j6ExHV5VgeNLyU4gM/E/fSpqdAn8vMhg=,tag:dKFW2grq00xVbNMmysoZ1g==,type:comment]
#ENC[AES256_GCM,data:suTn9APrIz6mkrF7DQo2WVIlyFRQdr9E07AOI3BZKnDiubTXGrcLXt6+p8tnKXMXOyWLvg9Ma/11PsjKVQ/5yI2Ba4vM8rKNGqZz9jt7aJ9WlXpHOTls2Q==,iv:KTEM5vbA/DT26xXgwLIRLJHFM0qFDGDhigiya6RHP6I=,tag:kn4CPundfcX+XyC1cKoamA==,type:comment]
auth:
    authentik:
        postgres_password: ENC[AES256_GCM,data:zP5tWzn5LQpTXTXBFbRqcPfjOOIFqfp/G6omiKssSm/aL8PO6VO87+sEr4o=,iv:7/+mNcTnzK3iBeEcOBDFHjxXwEs0P9CUoCJPmEaAkp8=,tag:/l63EfTW8FWvAVgERs9gCg==,type:str]
        secret_key: ENC[AES256_GCM,data:roovow+f8HH0XmC+j22dJI/3N6mUqRnfDTZRWaeuIO879dytnvUnZPcGLSvHOxgvwaU8OWWpNlcSZyCT81dbSw==,iv:z7qmC9SpehQawbsInRNF9tq6e4/NzcXhLZoHQKkCblo=,tag:DICC+BkW6wt3e6BdcqbX4A==,type:str]
apps:
    static:
        auth_demos:
            oidc:
                client_id: ENC[AES256_GCM,data:X6UU0XyMUkYWHAxXZSM=,iv:vj4aXy7gFVSF6yVOF6G2d+tS3MDVdL45Lf+Sb87qx8o=,tag:DEiUzPkCy4M2zcFPSBYoeg==,type:str]
                client_secret: ENC[AES256_GCM,data:vG8GpaA3lbuMn+9N0MUR2yQllN8TQYwcLCEKKOrfIY0tGEAWhqsYILxthcY=,iv:eudllFBQlUbJ0jQI4blv48voIJEyYHysQ1pOogCWDks=,tag:Vgf76hWxS3GVLEIrh1x03g==,type:str]
                session_secret: ENC[AES256_GCM,data:bDh8PjpH06aKQbEE8GavR6aI4iliSEccW+O6GTAN1MdiYnultdXQNd+iAb4=,iv:DkdbwNTjb7VolZge2CS6vFdx3hZ5d+lRnp0e7EZgxl4=,tag:4wBlNIQxxrBj2UflknhO7Q==,type:str]
            jwt_api:
                client_id: ENC[AES256_GCM,data:CoAsmCkt2/bRMf+sdtxV7x4=,iv:Ij/Y1KZBye9BaCy9vZhtwH6alOw2iQuMNeF6oD+Ae0I=,tag:VaACVJd12QTPOCShg9NB3Q==,type:str]
                client_secret: ENC[AES256_GCM,data:KywQsevkX52S41WyCY24EtbWkQP7iqtd/sC1NQw9iCB8Hta8u/4BXNDQoyY=,iv:RzZt2SXUNpuKEMoDARsoPCUx2SRN8NAOdH8A7gTZ50Q=,tag:Knusbznt2uYtoRq+NepFdQ==,type:str]
            demo_users:
                demo_user_password: ENC[AES256_GCM,data:3KXHCimPkyWKaVY0JIb3E/jlWMxhfnYk,iv:NuKOkmnswdoDPo/qXoZsJRqyC62wj0RZ8PO8YYD/6HU=,tag:97U0WPqqHir5eOcaxmFqHA==,type:str]
                ops_user_password: ENC[AES256_GCM,data:ifJo0xqntHMEuEdDNRoTpP8nwZn3Sf5x,iv:0H4gbbcD4jryyOzMfJ1F6eOhsaZmy8lU4V5MGHF3g7Q=,tag:R+cvAnB48nzyFk7rD2gOGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U0VPdS9lZXIzeE16VEE0
            OGNnS2lEVWNJMlFFa1M2UjN2VUlwM1I1THk4CmhEZGVkTThlVzhtV3VUcXRRaVVU
            dE5PSUEyMjlBUURQazVmMi9kVVRHVHMKLS0tIEFCRnJVQi9YR1B4bXdoaDUxVXox
            clU5QVRQRW1CV2htQ3k1aU1kV0NJMUEK4DJrO9IelY6k6RofzCqmVKLGldGmP3rW
            GfEnDA9f7T1WoBiYPpmawJu/qamGPDq1WekjUkR0dGTNjjeUq8dCVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dp6nnhd3j5l2waahhttgyzrs4sf4m7nk79r0htf4wgwwaajtegjsnjdfur
    lastmodified: "2026-05-18T14:35:06Z"
    mac: ENC[AES256_GCM,data:a6nJyZcRJwVQ/3PM+E+1wa4XAVCANJoBF8UuiVBPo8NOi2CsRQ4FuV95GpGLPmxOZZo7rsxUrcAfH16JXrnrHE+qYg28jxWTdoErVYdUEsfQfio4YWZ3Z/iSqjtthRnl/F/1oP8TC4Y+GV4U4jr2U1q7zVShxx/9IehQxD3jpBY=,iv:LMFcvnuXcsuEH4n4L4Wf/hqod6KO75MqpQQ/XhRtSqs=,tag:fjmD14DkdhkDvkmFY9dLpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
