#ENC[AES256_GCM,data:IPQ2e6FKTgT3LCyYcCPLUYCnjfadziSNjzJlOey7DU9/c3iY/IRCMXgQEtQN++eKxZf335Wz6w==,iv:8ue7czQeIFo/8l70vcGJuvJKaqp6b7mYAET9LjMPKmY=,tag:L03TDgae0jKv3MuwHnkL9Q==,type:comment]
#ENC[AES256_GCM,data:+dH5Lnx5iI24PL4D4ueoWAYY22GK96ym6hr4nmAoqt4V7x24dFcABBy67poMPSAs3E/ZwNlkqytpVKp+HVdKyK1kQ9902Y5TNoAJXyNMdnWyf+v8vxVaQw==,iv:Z9XfWpR7yk7nEkOlTUOYuivgFC4xfkoG/opG2FXmjDI=,tag:k98a/VnlubrI/0Id1W5W9g==,type:comment]
auth:
    authentik:
        postgres_password: ENC[AES256_GCM,data:qo6n0eCY1qJ96xAJv9JaigOWecu/N5etplZefGNSrGv2TroK8RKyy5OukqA=,iv:S/o/CeYtbUdR4VDCNb2/7L6RUEN6ad3eRcoAscEyvuo=,tag:/fWTuzZtzx7q3sl26ZVfkQ==,type:str]
        secret_key: ENC[AES256_GCM,data:c+sHDeZTZY9h8NAZh+ilCp0ygXat3yGK30V/PV0aS0TfrKvONDlSck6+XGlCQeh5TvEnGfk5Xqijs8ryK6x4nQ==,iv:BVcs/jF/uCTf/l9UIp1qKBtLOZz57uYK412Kw/yJCpY=,tag:Cg5obbpWZi3pC0fzcycvSg==,type:str]
        bootstrap_email: ENC[AES256_GCM,data:XBQBmkQTzRMMByiwl+GPu+r1Dw==,iv:dh2CA+vvWj4CHbPGvKfKO4Evm8KKtG6q9EFgt0t5a6M=,tag:PF2ra0NAfiyJ2EWsW9clRQ==,type:str]
        bootstrap_password: ENC[AES256_GCM,data:lxU8Mxjgd19Cp5c=,iv:H85wP/t5uVGb2siO9SK5e5wOgvjQ4DAKSFmPzhtBqB8=,tag:yzAUn8Fpq4/0Chax084YlA==,type:str]
apps:
    static:
        auth_demos:
            oidc:
                client_id: ENC[AES256_GCM,data:eFjI6B1pvgiZjPlB9nQ=,iv:9g2X0AKwHjNjDFvKDlox89AExoBlZJIFpt+2hRrMGLU=,tag:OSnpObqJLjplFb2apeOLrQ==,type:str]
                client_secret: ENC[AES256_GCM,data:zSf1pX7qdQyzGSb8a5tFWgG6NAbpXiKihwRGyBS5w7MbhHjEZR/7geJa3IA=,iv:xNWx81bpt5PhvaYkY70sPfRcleN0h+bceqlyPg42IU0=,tag:UKgr3H1wBPDHFhjMxXHaoQ==,type:str]
                session_secret: ENC[AES256_GCM,data:XizWZEdZBrh+KqmKTXuljbJdXe5Jnnu0DoqDfVmcetkN7CkUx6zO4n41zKE=,iv:peKVVFSlhKbhi1dL/5PIt3x6MlgGQ7oQIk+nJSB4Whw=,tag:sDDwaIMTcoBDUojdrbaDaw==,type:str]
            jwt_api:
                client_id: ENC[AES256_GCM,data:CVrbOmNM++0stMBzDMFW8X4=,iv:NHL4xqT23KNCr8f6ne8pljz0t4+qp6akVnCDQzl3yhU=,tag:U0EAJMof6M7rYQQkHGclpQ==,type:str]
                client_secret: ENC[AES256_GCM,data:pM7UpCVNvuUjpuTmxYXE90h0EtslBfBW48+qB3FwsdYiiR1lCnEUxg4aPwE=,iv:ytHaynOCHYX3XWdT+74LE5xUVgChVNlFd7kU3OqfORU=,tag:IQC8eyPIrV5hPiLD6S3n5g==,type:str]
            demo_users:
                demo_user_password: ENC[AES256_GCM,data:qghGk8V9jgqcUc94Mk6tOIPfT5wwuHy2,iv:91L6k0kYxhn9q6TAEkRiT+SoxFpZmCvpybaksEh+3Sg=,tag:I/Ow6Fnp+QQbHXm1RMhhLQ==,type:str]
                ops_user_password: ENC[AES256_GCM,data:U861KYeeFvXDdlUsMZph820A3io7v84i,iv:wtQ1ijk4l90NsR39FXz0rz9p9Tb9CIx7lq9loNQRrUY=,tag:YD4v4Hjxq7HaUHJLlsxHvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbG9rcmlSaXJnejdLaElk
            aS9CVHF3RVBqTXZGU1ROeHpjbXdrNERuT1hvCjVQY0NyUFNzVlhuYUNzVENDcFpJ
            d3J2VFoyVEsxK05sU3QyUUNSVkUxdzAKLS0tIG12bnFHUjdSaW5qMEU2cjhvS0Fw
            Smp2RG9VZ2krd0h0YjMrNVlaLzBRb28K9/xOjLOm7w65ctU6ZblcHjbGVptXF2c1
            aZ9Rq/X/jPDx9aruzI6Vmc9QIqPI69plV9US/Dq8f1MycVZxkDcEqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dp6nnhd3j5l2waahhttgyzrs4sf4m7nk79r0htf4wgwwaajtegjsnjdfur
    lastmodified: "2026-05-18T15:55:34Z"
    mac: ENC[AES256_GCM,data:nv9f4MzAS4Bvxr5MoR1lj0vcMPBda3V5O8cpBMwmiHJhaLJWIjqhMxYByppHWI+ELFRe5BQtZF2cZgW6Wiaib9/HZFMLmDW5DQLxdVGknNOUzkmw4xJfz4KeaJI609VwAGPtkoBb8JqUidSZeXeQbssDGgCcpCPQEQeT6P/zP/s=,iv:ySQbj9+1+IU6i192rpgWWmGyfOKQWgPeEKI2k0+2q8Y=,tag:9yIkFnknWmpZIZ9nMHnf0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
