#ENC[AES256_GCM,data:drf3rBxxse4VyKwAnZ3z4hZ57x++4c9anIA9e/Wgf8HeE/E1TXmPf1w+owOOV5maq9nuKlbJQw==,iv:xj3NxEe/66QJ/5ahNte1w/Ii6nHTrAsG1BJW26JPYAs=,tag:B+h0UFajCLEC2YeQ4EDp0w==,type:comment]
#ENC[AES256_GCM,data:XBQsyj8VNA9NSeYPWjPX9q4sBtEBTuCnb6EkObDwgVhchRR5iEMxe6NVLK1+XD2r5dfPkrm8boO9AgSr+KccTgkfOKv77ajiaM1psZDTl5u7JogOUchgcA==,iv:cEHoi+0fp2Dyp40Gv8tss1vkQsQ9b0u/zbpuhjstIBg=,tag:rgsQ+KW5BxcZ6nIKz42CAA==,type:comment]
auth:
    authentik:
        postgres_password: ENC[AES256_GCM,data:IrJfxjep7HFh+AFuKN99kxc6YJAca4PXz2rSHZ7n6rJH79MNcJVZJszZaBk=,iv:7KXCAYHEfGzKrJC3vNd+wp/PgX0enVGf2gFgdAYvPEs=,tag:wtZvDTWu8rjQzJZQhIl2rw==,type:str]
        secret_key: ENC[AES256_GCM,data:0YOnV5MxHaIGqI0y5kkNnXuqrHdHri4CwK5ZsHvaPIiZrYZ6OgA9ujZ3p/el2Ykc4ikwo1zsAKSxdTNq+ZSDkQ==,iv:1ZWa1ppnRMgbgQYerabPgqQZlbiPeSiaxnyxEaUFFyM=,tag:QG4U6fJ+Ce2CtDPmIL7Ojw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUDdVOXdqNzVGblRiNVJY
            cWdCS0hzY1JsSnlQNjg5QTE0bTZhdGtjNDNzCktmOTlxNDB4QVh5aHVldkF5dmxF
            a1poMDdCaXZ6ZFNvOFVoTE1ZY3FVRVUKLS0tIHBydFhhNzJtTVBKeHhWc3JLdlR3
            d1RuSWVaRm1hZG4zYUFsOFJPbDR4TU0Ku5Q1AkbVnSHexWkJOQkY2H+JxLIye30H
            piZzpZ6Z+6sl/y4BKQAIBo0iPqHLk4nYBsYgtz2KIyN/F6FTitgzZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dp6nnhd3j5l2waahhttgyzrs4sf4m7nk79r0htf4wgwwaajtegjsnjdfur
    lastmodified: "2026-05-18T09:29:02Z"
    mac: ENC[AES256_GCM,data:dTqnAfhNxcAOSry4oi0MkL3ullInxw7SzizHAX6dHbmBz+0cCjq2H3T9rKGB/Zm6rx3aglwqRPP955tdQN+B1Zu2bJx7qTLlOuB1gP/cIOnnY6TmOo9BOYgsDqsiCX/3KWVVvvKahweAUrFg8m0rygx7+5pOOH1yo0HyEb4CqLE=,iv:iB8IATpVPhBtabUQQJvEXoW9xqrJ0pMQEGU7wDzHF+U=,tag:e6R+RtIXJszPxuWjfTFzAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
